### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by akagabi** [hanford/uber-chrome#1]
Hey! Are you open for contributions?

**Comment by hanford** [comment]
absolutely! what are you thinking about adding?

**Comment by akagabi** [comment]
I find the tool very useful, but I noticed it have some UI/UX issues and I think I can be pretty useful with this. For example when you ask a car and the loader seems broken sometimes. I can make some stuff and you "judge" if it's useful 💃 What do you think?

**Comment by hanford** [comment]
would love it @fermijs !
